<br>
<br>
<div>
<img  style="float: left; padding-right: 100px; width: 350px" src="logai.png">
    </div>
    <br>
    <h2 align="center">LogAI</h2>
<hr>
<h4 align="center"><a href="https://t.co/IoL5C0LiPX">Zephania Reuben</a></h4>
<h4 align="center">September, 2025</h4>
<hr>
<h3 align="center">AfriAI Lab - ADVANCED AI SHORT COURSE TRAINING 2025
<br>
<hr>
DS2: NUMPY
</h3>
<hr>
<br>

<h3 style="color:green">OUTLINES:</h3>

- **<span>Introduction to NumPy**
- **<span>Getting started with NumPy</span>**
- **<span>Creating NumPy array</span>**
- **<span>NumPy arrays operations</span>**
- **<span>Inspecting size and shape</span>**
- **<span>Extracting items from an array</span>**
- **<span>Reverse rows and columns</span>**
- **<span>Computing mean,min,max on the ndarray</span>**
- **<span>Reshaping and Flattening multidimensional array</span>**
- **<span>Creating sequences, repetitions, and random numbers</span>**
- **<span>Getting unique items and count </span>**    

<h2 style="color:red; text-align:center;">Introduction to NumPy</h2>
<h2 style="color:green;">What is NumPy?</h2> 

- The NumPy library (NumPy, Numerical Python) is a package of high level mathematical functions and tools that are designed to work with the numpy array objects.
- A numpy array is a high performance multidimensional data structure more efficient than a <u>Python list</u>
- At the core, numpy provides the excellent ndarray objects, short for n-dimensional arrays.
- In a 'ndarray' object, it can store multiple items of the same data type.

<h2 style="color:green; text-align:center;">Getting started with NumPy</h2> 
  
<h3 style="color:green;">Installing Matplotlib</h3>  

- **Installing Matplotlib on Linux**
 - In the following table, we will present some of the common Linux distributions package names for Matplotlib and the tools we can use to install the package:
 
**Distribution**        |       **Package Name**
----------------------  |  -------------------------------
Debian or Ubuntu (And other Debian derivatives)                 |  <code>sudo apt-get install python-numpy</code>
Fedora                                                          |  <code>sudo dnf install numpy</code>
 
    

- **Installing Matplotlib on Windows**
 -  Open command line interface (CMD) use the next command to intall **Matplotlib**
 - <code>python -m pip install numpy</code>
 
<h3 style="color:green;">Testing our installation</h3>
 -  To ensure we have correctly installed Matplotlib and its dependencies, a very simple test can be carried out in the following manner:

In [1]:
import numpy
print("Numpy version : ", numpy.__version__)

Numpy version :  2.3.5


<h2 style="color:red; text-align:center;">Creating NumPy arrays</h2>

 - There are multiple ways to create a numpy array, most of which will be covered as you read this. However one of the most common ways is to create one from a list or a list like an object by passing it to the `np.array` function.

In [2]:
import numpy as np

In [3]:
f = np.array([1,3,5,6,9])

In [4]:
type(f)

numpy.ndarray

In [5]:
# Create an 1d array from a list

list1 = [0,1,2,3,4]

In [6]:
type(list1)

list

In [7]:
arr1d = np.array(list1)
# Print the array and its type
type(arr1d)

numpy.ndarray

In [8]:
arr1d

array([0, 1, 2, 3, 4])

In [9]:
# Create a 2d array from a list of lists
list2 = [[0,1,2], [3,4,5], [6,7,8]]

arr2d = np.array(list2)

arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# Create a float 2d array
arr2d_f = np.array(list2, dtype='float')

arr2d_f

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [11]:
# Convert to 'int' datatype
arr2d_f =  arr2d_f.astype('int')

In [12]:
arr2d_f.dtype

dtype('int64')

In [13]:
# Convert an array back to a list
arr2d_f.tolist()

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

<h2 style="color:red; text-align:center;">NumPy arrays operations</h2>
Different operations can be applied to numpy array like arithmetic and logical operations:-

In [14]:
import numpy as np 

x = np.array([[1,2,3,4],[5,6,7,8]]) # 2x4

y = np.array([[9,10,11,12],[13,14,15,16]]) # 2x4

In [15]:
np.add(x,y) # x+y

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

In [16]:
x + y

array([[10, 12, 14, 16],
       [18, 20, 22, 24]])

In [17]:
#Getting reminder
np.remainder(y,x)

array([[0, 0, 2, 0],
       [3, 2, 1, 0]])

In [18]:
#powering an ndarray
np.power(x,2)

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [19]:
#substracting a ndarray
y-x #np.subtract(y,x)

array([[8, 8, 8, 8],
       [8, 8, 8, 8]])

In [20]:
#logical operator
x<5

array([[ True,  True,  True,  True],
       [False, False, False, False]])

In [21]:
np.less(x,5)

array([[ True,  True,  True,  True],
       [False, False, False, False]])

In [22]:
np.greater_equal(y,10)

array([[False,  True,  True,  True],
       [ True,  True,  True,  True]])

<h2 style="color:red; text-align:center;">Inspecting shape and size</h2>

In [23]:
# Create a 2d array with 3 rows and 4 columns
list2 = [[1, 2, 3, 4],[3, 4, 5, 6], [5, 6, 7, 8]] # 3x4
arr2 = np.array(list2, dtype='float')
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [24]:
# shape
print('Shape: ', arr2.shape)

Shape:  (3, 4)


In [25]:
# dtype
print('Datatype: ', arr2.dtype)

Datatype:  float64


In [26]:
# size
print('Size: ', arr2.size)

Size:  12


<h2 style="color:red; text-align:center;">Extracting items from an array</h2>

- Elements are extracted from specific portions on an array using indexing starting with 0, something similar to python lists.
- But unlike lists, numpy arrays can optionally accept as many parameters in the square brackets as there is number of dimensions.

In [27]:
# Extract the first 2 rows and columns
arr2[:2, :2]

array([[1., 2.],
       [3., 4.]])

In [28]:
#list2[:2, :2]  # error

<h2 style="color:red; text-align:center;">Reverse rows and columns</h2>

- Reversing an array works like how you would do with lists, but you need to do for all the axes (dimensions) if you want a complete reversal.

In [29]:
# Reverse only the row positions
arr2[::-1, ]

array([[5., 6., 7., 8.],
       [3., 4., 5., 6.],
       [1., 2., 3., 4.]])

In [30]:
# Reverse the row and column positions
arr2[::-1, ::-1]

array([[8., 7., 6., 5.],
       [6., 5., 4., 3.],
       [4., 3., 2., 1.]])

<h2 style="color:red; text-align:center;">Computing mean,min,max on the ndarray</h2>

In [31]:
# mean
print("Mean value is: ", arr2.mean())

Mean value is:  4.5


In [32]:
#max 
print("Max value is: ", arr2.max())

Max value is:  8.0


In [33]:
#min
print("Min value is: ", arr2.min())

Min value is:  1.0


In [34]:
np.median(arr2)

np.float64(4.5)

In [35]:
np.std(arr2)

np.float64(1.9790570145063195)

<h2 style="color:red; text-align:center;">Reshaping and Flattening multidimensional array</h2>

- Reshaping is changing the arrangement of items so that shape of the array changes while maintaining the same number of dimensions.

- Flattening, however, will convert a multi-dimensional array to a flat 1d array. And not any other shape.



In [36]:
arr2

array([[1., 2., 3., 4.],
       [3., 4., 5., 6.],
       [5., 6., 7., 8.]])

In [37]:
arr2.reshape(2,6)

array([[1., 2., 3., 4., 3., 4.],
       [5., 6., 5., 6., 7., 8.]])

In [39]:
# Reshape a 3x4 array to 4x3 array
arr2.reshape(2, 3)

ValueError: cannot reshape array of size 12 into shape (2,3)

In [40]:
a = arr2.reshape(-1,1) # (12,1)

In [41]:
a.shape

(12, 1)

In [42]:
a

array([[1.],
       [2.],
       [3.],
       [4.],
       [3.],
       [4.],
       [5.],
       [6.],
       [5.],
       [6.],
       [7.],
       [8.]])

In [45]:
b = arr2.reshape(1,-1) # (1,12)

In [46]:
b.shape

(1, 12)

In [47]:
b

array([[1., 2., 3., 4., 3., 4., 5., 6., 5., 6., 7., 8.]])

In [48]:
A = (mxn)
B = (pxq) 

AxB = (n=p)

SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='? (2553111560.py, line 4)

In [ ]:
# Flatten it to a 1d array
arr2.flatten()

<h2 style="color:red; text-align:center;">Creating sequences, repetitions, and random numbers</h2>

The `np.arange` function comes handy to create customised number sequences as ndarray.You can set the starting and end positions using np.arange.

In [ ]:
# Lower limit is 0 be default
print(np.arange(5)) #[first_index,last_index-1,step] 

In [ ]:
# 0 to 9
print(np.arange(0, 10))  

In [ ]:
# 0 to 9 with step of 2
print(np.arange(0, 10, 2))  

In [ ]:
# 10 to 1, decreasing order
print(np.arange(10, 0, -2))

In [ ]:
a = [1,2,3] 

In [ ]:
# Repeat whole of 'a' two times
print('Tile:   ', np.tile(a, 3))

In [ ]:
# Repeat each element of 'a' two times
print('Repeat: ', np.repeat(a, 4))

In [ ]:
np.random.seed(10)

In [ ]:
# Random numbers between [0,1) of shape 2,2
np.random.seed(10)
print(np.random.rand(2,2))

In [ ]:
# Normal distribution with mean=0 and variance=1 of shape 2,2
print(np.random.randn(2,2))

In [ ]:
# Random integers between [0, 10) of shape 2,2
print(np.random.randint(0, 10, size=[2,2]))

In [ ]:
# One random number between [0,1)
print(np.random.random())

In [ ]:
# Random numbers between [0,1) of shape 2,2
print(np.random.random(size=[2,2]))

In [ ]:
# Pick 10 items from a given list, with equal probability
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10))  

In [ ]:
# Pick 10 items from a given list with a predefined probability 'p'
print(np.random.choice(['a', 'e', 'i', 'o', 'u'], size=10, p=[0.0, .4, 0.0, 0.0, 0.6]))  # picks more o's

<h2 style="color:red; text-align:center;">Getting unique items and count</h2>

In [ ]:
# Create random integers of size 10 between [0,10)
np.random.seed(30)
arr_rand = np.random.randint(0, 10, size=10)

In [ ]:
print(arr_rand)

In [ ]:
# Get the unique items and their counts
uniqs, counts = np.unique(arr_rand, return_counts=True)

In [ ]:
print("Unique items : ", uniqs)

In [ ]:
print("Counts       : ", counts)